atoms_0:
    frames_to_read: null
atoms_1:
    frames_to_read: null
atoms_2:
    frames_to_read: null
atoms_3:
    frames_to_read: null
atoms_4:
    frames_to_read: null
atoms_5:
    frames_to_read: null
