# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on:
  push:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mpi4py/setup-mpi@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
           auto-update-conda: true
           activate-environment: znlib
           python-version: ${{ matrix.python-version }}
      - name: Install CP2K
        shell: bash -l {0}
        run: |
          conda install -c conda-forge cp2k
          sudo apt update
          sudo apt install -y libopenmpi-dev
      - name: Install package
        shell: bash -l {0}
        run: |
          pip install -e git+https://github.com/zincware/znlib.git#egg=project[atomistic]
      - name: DVC Repro
        shell: bash -l {0}
        run: |
          dvc repro